---
apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: network-monitor-postgres:5432
    database: "${POSTGRES_DB}"
    user: "${POSTGRES_USER}"
    secureJsonData:
      password: "${POSTGRES_PASSWORD}"
    jsonData:
      sslmode: "disable"
