{
 "title": "Traffic Monitor",
 "tags": [
  "network",
  "monitoring"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Traffic Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Métricas por Cliente",
   "type": "table",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (client_id) client_name, availability, bandwidth_usage, quality_score FROM traffic_monitoring.metrics ORDER BY client_id, timestamp DESC;"
    }
   ]
  },
  {
   "title": "Disponibilidade Média",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT availability FROM traffic_monitoring.metrics"
    }
   ]
  },
  {
   "title": "Uso Médio de Banda",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT bandwidth_usage FROM traffic_monitoring.metrics"
    }
   ]
  }
 ]
}